require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CertificatesController do

  def mock_certificate(stubs={})
    @mock_certificate ||= mock_model(Certificate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all certificates as @certificates" do
      Certificate.stub(:all) { [mock_certificate] }
      get :index
      assigns(:certificates).should eq([mock_certificate])
    end
  end

  describe "GET show" do
    it "assigns the requested certificate as @certificate" do
      Certificate.stub(:find).with("37") { mock_certificate }
      get :show, :id => "37"
      assigns(:certificate).should be(mock_certificate)
    end
  end

  describe "GET new" do
    it "assigns a new certificate as @certificate" do
      Certificate.stub(:new) { mock_certificate }
      get :new
      assigns(:certificate).should be(mock_certificate)
    end
  end

  describe "GET edit" do
    it "assigns the requested certificate as @certificate" do
      Certificate.stub(:find).with("37") { mock_certificate }
      get :edit, :id => "37"
      assigns(:certificate).should be(mock_certificate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created certificate as @certificate" do
        Certificate.stub(:new).with({'these' => 'params'}) { mock_certificate(:save => true) }
        post :create, :certificate => {'these' => 'params'}
        assigns(:certificate).should be(mock_certificate)
      end

      it "redirects to the created certificate" do
        Certificate.stub(:new) { mock_certificate(:save => true) }
        post :create, :certificate => {}
        response.should redirect_to(certificate_url(mock_certificate))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved certificate as @certificate" do
        Certificate.stub(:new).with({'these' => 'params'}) { mock_certificate(:save => false) }
        post :create, :certificate => {'these' => 'params'}
        assigns(:certificate).should be(mock_certificate)
      end

      it "re-renders the 'new' template" do
        Certificate.stub(:new) { mock_certificate(:save => false) }
        post :create, :certificate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested certificate" do
        Certificate.stub(:find).with("37") { mock_certificate }
        mock_certificate.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :certificate => {'these' => 'params'}
      end

      it "assigns the requested certificate as @certificate" do
        Certificate.stub(:find) { mock_certificate(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:certificate).should be(mock_certificate)
      end

      it "redirects to the certificate" do
        Certificate.stub(:find) { mock_certificate(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(certificate_url(mock_certificate))
      end
    end

    describe "with invalid params" do
      it "assigns the certificate as @certificate" do
        Certificate.stub(:find) { mock_certificate(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:certificate).should be(mock_certificate)
      end

      it "re-renders the 'edit' template" do
        Certificate.stub(:find) { mock_certificate(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested certificate" do
      Certificate.stub(:find).with("37") { mock_certificate }
      mock_certificate.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the certificates list" do
      Certificate.stub(:find) { mock_certificate }
      delete :destroy, :id => "1"
      response.should redirect_to(certificates_url)
    end
  end

end
